### ISSUE TITLE
[Problem]: Does not build with `libplist` 2.3.0, which contains a breaking change.

### ISSUE THREAD

**Issue by reitermarkus** [mikebrady/shairport-sync#1674]
### What happened?

`libplist` 2.3.0 (Arch Linux) contains a breaking change for `plist_from_memory`, see https://github.com/libimobiledevice/libplist/releases/tag/2.3.0.

### Relevant log output

```
rtsp.c:1040:5: error: too few arguments to function ‘plist_from_memory’
 1040 |     plist_from_memory(message->content, message->contentlength, &the_plist);
```

```
/usr/include/plist/plist.h:828:17: note: declared here
  828 |     plist_err_t plist_from_memory(const char *plist_data, uint32_t length, plist_t *plist, plist_format_t *format);
```

### Configuration Information.

N/A

### How did you install Shairport Sync?

Built from source

### Check previous issues

- [X] Confirm

**Comment by reitermarkus** [comment]
Fixed by https://github.com/mikebrady/shairport-sync/pull/1675. Weird that this wasn't auto-closed by the PR.
